# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  # Database service with pgvector extension
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for caching and message queue
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API service
  backend-api:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app
      - app-storage:/app/storage
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - SUPABASE_URL=http://localhost:8000
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - STORAGE_PATH=/app/storage
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
      - db

  # Backend worker service for async tasks
  backend-worker:
    build:
      context: ./app/backend
      dockerfile: Dockerfile.worker
    volumes:
      - ./app/backend:/app
      - app-storage:/app/storage
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - SUPABASE_URL=http://localhost:8000
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - STORAGE_PATH=/app/storage
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
      - db

  # Frontend service for development
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./app/frontend:/app
    environment:
      - VITE_SUPABASE_URL=http://backend-api:8000
      - VITE_SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - VITE_API_BASE_URL=http://backend-api:8000/api/v1
    depends_on:
      - backend-api

volumes:
  redis-data:
  postgres-data:
  app-storage: